'use client'
import { useEffect, useState } from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
import { QueryClient, QueryClientProvider } from 'react-query'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const queryClient = new QueryClient()
export default function RootLayout({ children }) {
  // const [showChild, setShowChild] = useState(false);
  useEffect(() => {
    import('preline')
  }, [])
  // if (!showChild) {
  //   return null;
  // }
  return (
    
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
          {children} 
        </QueryClientProvider></body>
    </html>
   
  )
}
